language: ruby
os: linux
dist: xenial
services:
  - docker

before_install:
  - docker build -t gbrody/gitbook -f Dockerfile.dev .

script:
  - docker run -e CI=true gbrody/gitbook npm run test -- --coverage